name: Node CI
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm intsall and build webpack
        run: |
          npm install
          npm run build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [uuntu-latest, window-2016]
        node-version: [12.x, 14.x]
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matix.node-version }}
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
